### ISSUE TITLE
Not an issue per se, but more of a request

### ISSUE THREAD

**Issue by plartoo** [oakmac/autocompletejs#92]
Hi Chris,

Thank you for writing 'autocompletejs'. It is such a nice, neat and compact library that I found really useful for my projects. :) I'd like to request a feature where the suggestion list does NOT show the ones that are already added in the search_bar (the selected list). For example, if all available options are ['Orange', 'Apple', 'Grape', 'Kiwi'] and the user has already chosen ['Orange','Apple'], then the suggestion list should only show ['Grape','Kiwi']. 

Again, thank you so much for this really neat and helpful work of yours!

Cheers,
plartoo

**Comment by oakmac** [comment]
Thanks for the kind words; I'm glad you enjoy the library :)

I think you can accomplish what you are describing using the [`matchOptions` function](http://autocompletejs.com/docs#list_object:matchOptions). You will need to filter out the options that are already in the list.

**Comment by plartoo** [comment]
Hi Chris,

Thank you for the reply and a pointer to look at. :) I couldn't get `matchOptions` to work, but I was able to hack using `onChange` like [this](https://github.com/plartoo/others/blob/main/dashboard/scatter.html#L56). Have a restful weekend!
