### ISSUE TITLE
Limit on the number of elements in list

### ISSUE THREAD

**Issue by migvel** [oakmac/autocompletejs#93]
Hello, 

looks that there is a limit in the list, whenever is higher than around 1500 it gives 
an error AutoComplete Error 1005: You must include at least one List Object on lists.

Any idea on this?

Thanks.

**Comment by oakmac** [comment]
Can you post the code example that generates this error?

**Comment by migvel** [comment]
Hello,

is just a formal initialization of the library,

   ```
 var config = {
		lists: {
		    regions: urbans
		},
		maxTokenGroups: 1
	    };
	var widget = new AutoComplete('fast-search',config);    
```


var urbans = ['string1','string2', ...] the original array gives that error, but if I reduce the size it works properly.

Or do you think it can be an array element that is triggering the error?

Thanks.

**Comment by oakmac** [comment]
> Or do you think it can be an array element that is triggering the error?

Difficult to tell without seeing the full code. Can you post the full code sample here or as a [gist](https://gist.github.com)?

**Comment by migvel** [comment]
Thanks for the reply, I'll dig a bit if there is some problem with an element and get back.

Regards.

**Comment by migvel** [comment]
It was caused by some null elements in the array.

Thanks.
